<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2013 rel. 2 sp2 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:altova="http://www.altova.com" xmlns:altovaext="http://www.altova.com/xslt-extensions" xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:sps="http://www.altova.com/StyleVision/user-xpath-functions" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" exclude-result-prefixes="altova altovaext clitype fn iso4217 ix java link sps xbrldi xbrli xlink xs xsi">
	<xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN"/>
	<xsl:param name="SV_OutputFormat" select="'HTML'"/>
	<xsl:variable name="XML1" select="/"/>
	<xsl:variable name="altova:nPxPerIn" select="96"/>
	<xsl:template match="/">
		<html>
			<head>
				<title/>
				<meta name="generator" content="Altova StyleVision Enterprise Edition 2013 rel. 2 sp2 (http://www.altova.com)"/>
				<meta http-equiv="X-UA-Compatible" content="IE=5"/>
				<xsl:comment>[if IE]&gt;&lt;STYLE type=&quot;text/css&quot;&gt;.altova-rotate-left-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=3)} .altova-rotate-right-textbox{filter: progid:DXImageTransform.Microsoft.BasicImage(rotation=1)} &lt;/STYLE&gt;&lt;![endif]</xsl:comment>
				<xsl:comment>[if !IE]&gt;&lt;!</xsl:comment>
				<style type="text/css">.altova-rotate-left-textbox{-webkit-transform: rotate(-90deg) translate(-100%, 0%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(-90deg) translate(-100%, 0%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(-90deg) translate(-100%, 0%); -ms-transform-origin: 0% 0%;}.altova-rotate-right-textbox{-webkit-transform: rotate(90deg) translate(0%, -100%); -webkit-transform-origin: 0% 0%;-moz-transform: rotate(90deg) translate(0%, -100%); -moz-transform-origin: 0% 0%;-ms-transform: rotate(90deg) translate(0%, -100%); -ms-transform-origin: 0% 0%;}</style>
				<xsl:comment>&lt;![endif]</xsl:comment>
				<style type="text/css">@page { margin-left:0.6in; margin-right:0.6in; margin-top:0.79in; margin-bottom:0.79in } @media print { br.altova-page-break { page-break-before: always; } }</style>
			</head>
			<body>
				<xsl:for-each select="$XML1">
					<xsl:for-each select="MICEX_DOC">
						<xsl:if test="string-length(DOC_REQUISITES/@DOC_NO) &gt; 0">
							<div>
								<span style="font-family:Arial; font-size:10; font-style:italic; ">
									<xsl:text>Исх. №: </xsl:text>
								</span>
								<xsl:for-each select="DOC_REQUISITES">
									<xsl:for-each select="@DOC_NO">
										<span style="font-family:Arial; font-size:10; font-style:italic; font-weight:bold; ">
											<xsl:value-of select="string(.)"/>
										</span>
									</xsl:for-each>
									<span style="font-family:Arial; font-size:10; font-style:italic; ">
										<xsl:text> от </xsl:text>
									</span>
									<xsl:for-each select="@DOC_DATE">
										<span style="font-family:Arial; font-size:10; font-style:italic; font-weight:bold; ">
											<xsl:variable name="altova:seqContentStrings_0">
												<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00')"/>
												<xsl:text>.</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00')"/>
												<xsl:text>.</xsl:text>
												<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000')"/>
											</xsl:variable>
											<xsl:variable name="altova:sContent_0" select="string($altova:seqContentStrings_0)"/>
											<xsl:value-of select="$altova:sContent_0"/>
										</span>
									</xsl:for-each>
								</xsl:for-each>
							</div>
						</xsl:if>
						<table style="border:0; border-collapse:collapse; " border="1" width="100%">
							<xsl:variable name="altova:CurrContextGrid_1" select="."/>
							<tbody>
								<tr style="height:19px; ">
									<td style="border:0; font:Arial; font-size:12; font-weight:bold; ">
										<span style="font-family:Arial; ">
											<xsl:text>ОАО Московская Биржа</xsl:text>
										</span>
									</td>
									<td style="border:0; "/>
									<td style="border:0; "/>
									<td style="border:0; "/>
									<td style="border:0; "/>
									<td style="border:0; "/>
									<td style="border:0; "/>
									<td style="border:0; "/>
									<td style="border:0; font:Arial; font-size:12; font-weight:bold; text-align:right; ">
										<span style="font-family:Arial; font-size:12; ">
											<xsl:text>CUX07</xsl:text>
										</span>
									</td>
								</tr>
							</tbody>
						</table>
						<xsl:for-each select="CUX07">
							<div style="font:Arial; font-family:Arial; font-size:14; font-weight:bold; text-align:center; ">
								<span style="font-size:.; ">
									<xsl:text>Выписка из реестра подтверждений КЦ</xsl:text>
								</span>
							</div>
							<div style="font-family:Arial; font-size:12; font-weight:bold; text-align:center; ">
								<span>
									<xsl:text>Дата заключения сделок:&#160; </xsl:text>
								</span>
								<xsl:for-each select="@ReportDate">
									<span style="font:Arial; font-family:Arial; font-size:12; ">
										<xsl:variable name="altova:seqContentStrings_2">
											<xsl:value-of select="format-number(number(substring(string(string(.)), 9, 2)), '00')"/>
											<xsl:text>.</xsl:text>
											<xsl:value-of select="format-number(number(substring(string(string(.)), 6, 2)), '00')"/>
											<xsl:text>.</xsl:text>
											<xsl:value-of select="format-number(number(substring(string(string(string(.))), 1, 4)), '0000')"/>
										</xsl:variable>
										<xsl:variable name="altova:sContent_2" select="string($altova:seqContentStrings_2)"/>
										<xsl:value-of select="$altova:sContent_2"/>
									</span>
								</xsl:for-each>
							</div>
							<br/>
							<span style="font-family:Arial; font-size:12; ">
								<xsl:text>Биржа: </xsl:text>
							</span>
							<span style="font-family:Arial; font-size:12; font-weight:bold; ">
								<xsl:text>ОАО Московская биржа</xsl:text>
							</span>
							<br/>
							<span style="font-family:Arial; font-size:12; ">
								<xsl:text>Участник торгов:</xsl:text>
							</span>
							<span>
								<xsl:text>&#160;</xsl:text>
							</span>
							<xsl:for-each select="@FirmId">
								<span style="font-family:Arial; font-size:12; font-weight:bold; ">
									<xsl:value-of select="string(.)"/>
								</span>
							</xsl:for-each>
							<span style="font-weight:bold; ">
								<xsl:text>, </xsl:text>
							</span>
							<xsl:for-each select="@FirmName">
								<span style="font-family:Arial; font-size:12; font-weight:bold; ">
									<xsl:value-of select="string(.)"/>
								</span>
							</xsl:for-each>
							<br/>
							<xsl:for-each select="SETTLE">
								<span style="font-family:Arial; font-size:12; ">
									<xsl:text>Расчетный код: </xsl:text>
								</span>
								<xsl:for-each select="@ExtSettleCode">
									<span style="font-family:Arial; font-size:12; font-weight:bold; ">
										<xsl:value-of select="string(.)"/>
									</span>
								</xsl:for-each>
								<br/>
								<xsl:for-each select="SESSION">
									<span style="font-family:Arial; font-size:12; ">
										<xsl:text>Наименование сессии: </xsl:text>
									</span>
									<xsl:for-each select="@SessionName">
										<span style="font-family:Arial; font-size:12; font-weight:bold; ">
											<xsl:value-of select="string(.)"/>
										</span>
									</xsl:for-each>
									<br/>
									<br/>
									<xsl:for-each select="CURRPAIR">
										<xsl:for-each select="SECURITY">
											<xsl:for-each select="SETTLEDATE">
												<table style="background-color:#e1e1e1; border:0; border-collapse:collapse; font-family:Arial; font-size:12; " border="1" width="100%">
													<xsl:variable name="altova:CurrContextGrid_3" select="."/>
													<tbody>
														<tr>
															<td style="border:0; width:1.06in; ">
																<span>
																	<xsl:text>Инструмент:</xsl:text>
																</span>
															</td>
															<td style="border:0; width:0.28in; "/>
															<td style="border:0; font-weight:bold; text-align:left; width:1.35in; ">
																<span>
																	<xsl:value-of select="../@SecShortName"/>
																</span>
															</td>
															<td style="border:0; width:0.14in; "/>
															<td style="border:0; width:1.58in; ">
																<span>
																	<xsl:text>Валюта лота:</xsl:text>
																</span>
															</td>
															<td style="border:0; font-weight:bold; text-align:left; width:1.74in; ">
																<span>
																	<xsl:value-of select="../../@CurrencyName"/>
																</span>
															</td>
															<td style="border:0; width:0.09in; "/>
															<td style="border:0; width:1.09in; "/>
															<td style="border:0; font-weight:bold; "/>
														</tr>
														<tr>
															<td style="border:0; width:1.06in; ">
																<span>
																	<xsl:text>Дата исполнения:</xsl:text>
																</span>
															</td>
															<td style="border:0; width:0.28in; "/>
															<td style="border:0; font-weight:bold; text-align:left; width:1.35in; ">
																<span>
																	<xsl:variable name="altova:seqContentStrings_4">
																		<xsl:value-of select="format-number(number(substring(string(@SettleDate), 9, 2)), '00')"/>
																		<xsl:text>.</xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(@SettleDate), 6, 2)), '00')"/>
																		<xsl:text>.</xsl:text>
																		<xsl:value-of select="format-number(number(substring(string(string(@SettleDate)), 1, 4)), '0000')"/>
																	</xsl:variable>
																	<xsl:variable name="altova:sContent_4" select="string($altova:seqContentStrings_4)"/>
																	<xsl:value-of select="$altova:sContent_4"/>
																</span>
															</td>
															<td style="border:0; width:0.14in; "/>
															<td style="border:0; width:1.58in; ">
																<span>
																	<xsl:text>Сопряж. валюта:</xsl:text>
																</span>
															</td>
															<td style="border:0; font-weight:bold; text-align:left; width:1.74in; ">
																<span>
																	<xsl:value-of select="../../@CoCurrencyName"/>
																</span>
															</td>
															<td style="border:0; width:0.09in; "/>
															<td style="border:0; width:1.09in; ">
																<span>
																	<xsl:text>Котировки за:</xsl:text>
																</span>
															</td>
															<td style="border:0; font-weight:bold; ">
																<span>
																	<xsl:value-of select="../@FaceValue"/>
																</span>
																<span>
																	<xsl:text> ед. валюты лота</xsl:text>
																</span>
															</td>
														</tr>
													</tbody>
												</table>
												<xsl:for-each select="GROUP">
													<xsl:choose>
														<xsl:when test="@TradeGroup = &quot;S&quot;">
															<span style="font-family:Arial; font-size:12; font-style:italic; ">
																<xsl:text>Подтверждения КЦ по сделкам, входящим в сделку своп</xsl:text>
															</span>
														</xsl:when>
														<xsl:when test="@TradeGroup = &apos;B&apos;">
															<span style="font-family:Arial; font-size:12; font-style:italic; ">
																<xsl:text>Подтверждения КЦ по сделкам, входящим в сделку с Бивалютной корзиной</xsl:text>
															</span>
														</xsl:when>
														<xsl:otherwise/>
													</xsl:choose>
													<xsl:for-each select="MAINSEC">
														<xsl:choose>
															<xsl:when test="../@TradeGroup = &quot;S&quot;">
																<table style="border:0; border-collapse:collapse; font-family:Arial; font-size:12; " border="1">
																	<xsl:variable name="altova:CurrContextGrid_5" select="."/>
																	<tbody>
																		<tr>
																			<td style="border:0; width:1.06in; ">
																				<span>
																					<xsl:text>Сделка своп:</xsl:text>
																				</span>
																			</td>
																			<td style="border:0; font-weight:bold; text-align:left; width:1.35in; ">
																				<span>
																					<xsl:value-of select="@MainSecShortName"/>
																				</span>
																			</td>
																		</tr>
																	</tbody>
																</table>
																<table style="border:0; border-collapse:collapse; font-family:Arial; font-size:12; " border="1" width="100%">
																	<xsl:variable name="altova:CurrContextGrid_6" select="."/>
																	<thead>
																		<tr>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Номер</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>заявки</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Номер</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>подтвер-</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ждения КЦ</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Время</xsl:text>
																				</span>
																				<br/>
																				<span>
																					<xsl:text>регистрации</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>подтвер-</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ждения КЦ</xsl:text>
																				</span>
																				<br/>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Направлен.</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span>
																					<xsl:text>Базовый</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>курс</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Курс</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>сделки</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Объем в</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>валюте лота,</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ед. валюты</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Объем в</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>сопряж. валюте,</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ед. валюты </xsl:text>
																				</span>
																			</th>
																			<th>
																				<span>
																					<xsl:text>АСП трейдера</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>Клирингового</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>центра</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span>
																					<xsl:text>Краткий</xsl:text>
																				</span>
																				<br/>
																				<span>
																					<xsl:text>код</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>Клиента</xsl:text>
																				</span>
																			</th>
																		</tr>
																	</thead>
																	<tbody>
																		<xsl:for-each select="RECORDS">
																			<tr>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:for-each select="@OrderNo">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:for-each select="@AcceptNo">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:for-each select="@TradeTime">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:choose>
																						<xsl:when test="@BuySell = &apos;B&apos;">
																							<span>
																								<xsl:text>К</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>П</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; ">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:for-each select="@BasePrice">
																						<xsl:choose>
																							<xsl:when test="../@Decimals  = 0">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_7">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_7" select="string($altova:seqContentStrings_7)"/>
																									<xsl:value-of select="$altova:sContent_7"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 1">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_8">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_8" select="string($altova:seqContentStrings_8)"/>
																									<xsl:value-of select="$altova:sContent_8"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 2">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_9">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_9" select="string($altova:seqContentStrings_9)"/>
																									<xsl:value-of select="$altova:sContent_9"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 3">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_10">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_10" select="string($altova:seqContentStrings_10)"/>
																									<xsl:value-of select="$altova:sContent_10"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 4">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_11">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.0000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_11" select="string($altova:seqContentStrings_11)"/>
																									<xsl:value-of select="$altova:sContent_11"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 5">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_12">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.00000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_12" select="string($altova:seqContentStrings_12)"/>
																									<xsl:value-of select="$altova:sContent_12"/>
																								</span>
																							</xsl:when>
																							<xsl:otherwise>
																								<span>
																									<xsl:variable name="altova:seqContentStrings_13">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.000000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_13" select="string($altova:seqContentStrings_13)"/>
																									<xsl:value-of select="$altova:sContent_13"/>
																								</span>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; ">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:for-each select="@Price">
																						<xsl:choose>
																							<xsl:when test="../@Decimals  = 0">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_14">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_14" select="string($altova:seqContentStrings_14)"/>
																									<xsl:value-of select="$altova:sContent_14"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 1">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_15">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_15" select="string($altova:seqContentStrings_15)"/>
																									<xsl:value-of select="$altova:sContent_15"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 2">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_16">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_16" select="string($altova:seqContentStrings_16)"/>
																									<xsl:value-of select="$altova:sContent_16"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 3">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_17">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_17" select="string($altova:seqContentStrings_17)"/>
																									<xsl:value-of select="$altova:sContent_17"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 4">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_18">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.0000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_18" select="string($altova:seqContentStrings_18)"/>
																									<xsl:value-of select="$altova:sContent_18"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 5">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_19">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.00000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_19" select="string($altova:seqContentStrings_19)"/>
																									<xsl:value-of select="$altova:sContent_19"/>
																								</span>
																							</xsl:when>
																							<xsl:otherwise>
																								<span>
																									<xsl:variable name="altova:seqContentStrings_20">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.000000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_20" select="string($altova:seqContentStrings_20)"/>
																									<xsl:value-of select="$altova:sContent_20"/>
																								</span>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; " nowrap="set">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:choose>
																						<xsl:when test="@BuySell = &apos;B&apos;">
																							<xsl:for-each select="@Quantity">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_21">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_21" select="string($altova:seqContentStrings_21)"/>
																									<xsl:value-of select="$altova:sContent_21"/>
																								</span>
																							</xsl:for-each>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>-</xsl:text>
																							</span>
																							<xsl:for-each select="@Quantity">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_22">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_22" select="string($altova:seqContentStrings_22)"/>
																									<xsl:value-of select="$altova:sContent_22"/>
																								</span>
																							</xsl:for-each>
																						</xsl:otherwise>
																					</xsl:choose>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; " nowrap="set">
																					<xsl:choose>
																						<xsl:when test="@BuySell = &apos;B&apos;">
																							<span>
																								<xsl:text>-</xsl:text>
																							</span>
																							<xsl:for-each select="@Value">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_23">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_23" select="string($altova:seqContentStrings_23)"/>
																									<xsl:value-of select="$altova:sContent_23"/>
																								</span>
																							</xsl:for-each>
																						</xsl:when>
																						<xsl:otherwise>
																							<xsl:for-each select="@Value">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_24">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_24" select="string($altova:seqContentStrings_24)"/>
																									<xsl:value-of select="$altova:sContent_24"/>
																								</span>
																							</xsl:for-each>
																						</xsl:otherwise>
																					</xsl:choose>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:for-each select="@UserId">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; " valign="middle">
																					<xsl:for-each select="@ClientCode">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																			</tr>
																		</xsl:for-each>
																		<tr>
																			<td colspan="6" style="border-bottom:0; border-left:0; border-right:0; text-align:right; ">
																				<span>
																					<xsl:text>Итого покупка:</xsl:text>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_25">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;B&apos; ]/@Quantity )), '###,##0')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_25" select="string($altova:seqContentStrings_25)"/>
																					<xsl:value-of select="$altova:sContent_25"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_26">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;B&apos; ]/@Value )), '###,##0.00')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_26" select="string($altova:seqContentStrings_26)"/>
																					<xsl:value-of select="$altova:sContent_26"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; "/>
																			<td style="border-bottom:0; border-left:0; border-right:0; "/>
																		</tr>
																		<tr>
																			<td colspan="6" style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:right; ">
																				<span>
																					<xsl:text>Итого продажа:</xsl:text>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_27">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;S&apos; ]/@Quantity )), '###,##0')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_27" select="string($altova:seqContentStrings_27)"/>
																					<xsl:value-of select="$altova:sContent_27"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_28">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;S&apos; ]/@Value )), '###,##0.00')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_28" select="string($altova:seqContentStrings_28)"/>
																					<xsl:value-of select="$altova:sContent_28"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; "/>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; "/>
																		</tr>
																	</tbody>
																</table>
															</xsl:when>
															<xsl:otherwise>
																<table style="border:0; border-collapse:collapse; font-family:Arial; font-size:12; " border="1" width="100%">
																	<xsl:variable name="altova:CurrContextGrid_29" select="."/>
																	<thead>
																		<tr>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Номер</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>заявки</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Номер</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>подтвер-</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ждения КЦ</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Время</xsl:text>
																				</span>
																				<br/>
																				<span>
																					<xsl:text>регистрации</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>подтвер-</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ждения КЦ</xsl:text>
																				</span>
																				<br/>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Направлен.</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Курс</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>сделки</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Объем в</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>валюте лота,</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ед. валюты</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span style="font-weight:bold; ">
																					<xsl:text>Объем в</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>сопряж. валюте,</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>ед. валюты </xsl:text>
																				</span>
																			</th>
																			<th>
																				<span>
																					<xsl:text>АСП трейдера</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>Клиригового</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>центра</xsl:text>
																				</span>
																			</th>
																			<th>
																				<span>
																					<xsl:text>Краткий</xsl:text>
																				</span>
																				<br/>
																				<span>
																					<xsl:text>код</xsl:text>
																				</span>
																				<br/>
																				<span style="font-weight:bold; ">
																					<xsl:text>Клиента</xsl:text>
																				</span>
																			</th>
																		</tr>
																	</thead>
																	<tbody>
																		<xsl:for-each select="RECORDS">
																			<tr>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:for-each select="@OrderNo">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:for-each select="@AcceptNo">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:for-each select="@TradeTime">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:choose>
																						<xsl:when test="@BuySell = &apos;B&apos;">
																							<span>
																								<xsl:text>К</xsl:text>
																							</span>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>П</xsl:text>
																							</span>
																						</xsl:otherwise>
																					</xsl:choose>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; ">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:for-each select="@Price">
																						<xsl:choose>
																							<xsl:when test="../@Decimals  = 0">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_30">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_30" select="string($altova:seqContentStrings_30)"/>
																									<xsl:value-of select="$altova:sContent_30"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 1">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_31">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_31" select="string($altova:seqContentStrings_31)"/>
																									<xsl:value-of select="$altova:sContent_31"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 2">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_32">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_32" select="string($altova:seqContentStrings_32)"/>
																									<xsl:value-of select="$altova:sContent_32"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 3">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_33">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_33" select="string($altova:seqContentStrings_33)"/>
																									<xsl:value-of select="$altova:sContent_33"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 4">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_34">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.0000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_34" select="string($altova:seqContentStrings_34)"/>
																									<xsl:value-of select="$altova:sContent_34"/>
																								</span>
																							</xsl:when>
																							<xsl:when test="../@Decimals  = 5">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_35">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.00000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_35" select="string($altova:seqContentStrings_35)"/>
																									<xsl:value-of select="$altova:sContent_35"/>
																								</span>
																							</xsl:when>
																							<xsl:otherwise>
																								<span>
																									<xsl:variable name="altova:seqContentStrings_36">
																										<xsl:value-of select="format-number(number(string(.)), '#,##0.000000')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_36" select="string($altova:seqContentStrings_36)"/>
																									<xsl:value-of select="$altova:sContent_36"/>
																								</span>
																							</xsl:otherwise>
																						</xsl:choose>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; " nowrap="set">
																					<span style="font-weight:bold; ">
																						<xsl:text>&#160;</xsl:text>
																					</span>
																					<xsl:choose>
																						<xsl:when test="@BuySell = &apos;B&apos;">
																							<xsl:for-each select="@Quantity">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_37">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_37" select="string($altova:seqContentStrings_37)"/>
																									<xsl:value-of select="$altova:sContent_37"/>
																								</span>
																							</xsl:for-each>
																						</xsl:when>
																						<xsl:otherwise>
																							<span>
																								<xsl:text>-</xsl:text>
																							</span>
																							<xsl:for-each select="@Quantity">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_38">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_38" select="string($altova:seqContentStrings_38)"/>
																									<xsl:value-of select="$altova:sContent_38"/>
																								</span>
																							</xsl:for-each>
																						</xsl:otherwise>
																					</xsl:choose>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:right; " nowrap="set">
																					<xsl:choose>
																						<xsl:when test="@BuySell = &apos;B&apos;">
																							<span>
																								<xsl:text>-</xsl:text>
																							</span>
																							<xsl:for-each select="@Value">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_39">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_39" select="string($altova:seqContentStrings_39)"/>
																									<xsl:value-of select="$altova:sContent_39"/>
																								</span>
																							</xsl:for-each>
																						</xsl:when>
																						<xsl:otherwise>
																							<xsl:for-each select="@Value">
																								<span>
																									<xsl:variable name="altova:seqContentStrings_40">
																										<xsl:value-of select="format-number(number(string(.)), '###,##0.00')"/>
																									</xsl:variable>
																									<xsl:variable name="altova:sContent_40" select="string($altova:seqContentStrings_40)"/>
																									<xsl:value-of select="$altova:sContent_40"/>
																								</span>
																							</xsl:for-each>
																						</xsl:otherwise>
																					</xsl:choose>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; ">
																					<xsl:for-each select="@UserId">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																				<td style="border-bottom:0; border-top:0; text-align:center; " valign="middle">
																					<xsl:for-each select="@ClientCode">
																						<span>
																							<xsl:value-of select="string(.)"/>
																						</span>
																					</xsl:for-each>
																				</td>
																			</tr>
																		</xsl:for-each>
																		<tr>
																			<td colspan="5" style="border-bottom:0; border-left:0; border-right:0; text-align:right; ">
																				<span>
																					<xsl:text>Итого покупка:</xsl:text>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_41">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;B&apos; ]/@Quantity )), '###,##0')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_41" select="string($altova:seqContentStrings_41)"/>
																					<xsl:value-of select="$altova:sContent_41"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_42">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;B&apos; ]/@Value )), '###,##0.00')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_42" select="string($altova:seqContentStrings_42)"/>
																					<xsl:value-of select="$altova:sContent_42"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; "/>
																			<td style="border-bottom:0; border-left:0; border-right:0; "/>
																		</tr>
																		<tr>
																			<td colspan="5" style="border-bottom:0; border-left:0; border-right:0; border-top:0; text-align:right; ">
																				<span>
																					<xsl:text>Итого продажа:</xsl:text>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_43">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;S&apos; ]/@Quantity )), '###,##0')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_43" select="string($altova:seqContentStrings_43)"/>
																					<xsl:value-of select="$altova:sContent_43"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; font-weight:bold; text-align:right; " nowrap="set">
																				<span style="font-weight:bold; ">
																					<xsl:text>&#160;</xsl:text>
																				</span>
																				<span>
																					<xsl:variable name="altova:seqContentStrings_44">
																						<xsl:value-of select="format-number(number(sum( RECORDS[@BuySell =&apos;S&apos; ]/@Value )), '###,##0.00')"/>
																					</xsl:variable>
																					<xsl:variable name="altova:sContent_44" select="string($altova:seqContentStrings_44)"/>
																					<xsl:value-of select="$altova:sContent_44"/>
																				</span>
																			</td>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; "/>
																			<td style="border-bottom:0; border-left:0; border-right:0; border-top:0; "/>
																		</tr>
																	</tbody>
																</table>
															</xsl:otherwise>
														</xsl:choose>
													</xsl:for-each>
												</xsl:for-each>
											</xsl:for-each>
											<br/>
										</xsl:for-each>
									</xsl:for-each>
								</xsl:for-each>
							</xsl:for-each>
						</xsl:for-each>
					</xsl:for-each>
				</xsl:for-each>
			</body>
		</html>
	</xsl:template>
</xsl:stylesheet>
